verbunden_promeande:
    type:     rest
    prefix:   /promenade
    resource: "@verbundenPromenadeBundle/Resources/config/routes-v1.yml"

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /
